services:
    #manager
    file.manager:
      class: FileBundle\Core\FileManager

    #Doctrine Listener
    file.subscriber.file_upload:
      class: FileBundle\Events\EventSubscriber\FileUploadSubscriber
      tags:
        - {name: doctrine.event_subscriber}
