blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /sonata_admin

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /sonata_admin

sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /sonata_admin

file:
    resource: '@FileBundle/Resources/config/routing.yml'

user:
    resource: '@UserBundle/Resources/config/routing.yml'