services:
    blog.blogs:
        class: BlogBundle\Service\BlogsService
        arguments: [ "@doctrine" ]
    blog.comments:
         class: BlogBundle\Service\CommentsService
         arguments: [ "@doctrine" ]
    blog.messages:
        class: BlogBundle\Service\MessagesService
        arguments: [ "@doctrine" ]
    blog.sessions:
        class: BlogBundle\Service\SessionsService
        arguments: ["@request_stack", "@doctrine"]
    blog.flash_listener:
        class: BlogBundle\Listener\FlashListener
        arguments: ["@session"]
        tags:
            - { name: kernel.event_subscriber }