services:
    blog.blogs:
        class: BlogBundle\Service\BlogsService
        arguments: [ "@doctrine" ]
    blog.sessions:
        class: BlogBundle\Service\SessionsService
        arguments: ["@request_stack", "@doctrine"]