login:
  path: /u_login
  defaults: { _controller: UserBundle:Security:login }

logout:
  path: /u_logout

register:
  path: /u_register
  defaults: { _controller: UserBundle:Security:register }

recover:
  path: /u_recover/{token}
  defaults: { _controller: UserBundle:Security:recover, token: null }

user:
  path: /u_user

user_password_recover:
  path: /u_user/recover_password
  defaults: { _controller: UserBundle:User:recoverPassword }