login:
  path: /login
  defaults: { _controller: UserBundle:Security:login }

logout:
  path: /logout

register:
  path: /register
  defaults: { _controller: UserBundle:Security:register }

user:
  path: /user

user_profile:
  path: /user/profile
  defaults: { _controller: UserBundle:User:profile }

user_profile_view:
  path: /user/{id}/profile
  defaults: { _controller: UserBundle:User:userProfile }

user_edit:
  path: /user/edit
  defaults: { _controller: UserBundle:User:edit }

recover:
  path: /recover/{token}
  defaults: { _controller: UserBundle:Security:recover, token: null }

user_password_recover:
  path: /user/recover-password
  defaults: { _controller: UserBundle:User:recoverPassword }