login:
  path: /u_login
  defaults: { _controller: UserBundle:Security:login }

logout:
  path: /u_logout

register:
  path: /u_register
  defaults: { _controller: UserBundle:Security:register }

recover:
  path: /recover/{token}
  defaults: { _controller: UserBundle:Security:recover, token: null }

user:
  path: /user

user_profile:
  path: /user/profile
  defaults: { _controller: UserBundle:User:profile }

user_edit:
  path: /user/edit
  defaults: { _controller: UserBundle:User:edit }

user_password_recover:
  path: /user/recover_password
  defaults: { _controller: UserBundle:User:recoverPassword }