security:
    encoders:
      UserBundle\Entity\User:
        algorithm: sha1
        encode_as_base64: false
        iterations: 512

    providers:
        main:
            entity:
                class: UserBundle\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            http_basic: ~
            provider: main
            form_login:
                login_path: /login
                check_path: /login
            logout:
                path: /logout

    access_control:
        - { path: ^/user, roles: ROLE_USER }